blueprint:
  name: Underfloor heating control
  description: ''
  domain: automation
  input:
    switch:
      name: Switch
      description: Switch to turn on/off
      selector:
        device: {}
    indoor_temperature:
      name: Indoor temperature
      description: Indoor temperature
      selector:
        entity: {}
    requested_temperature:
      name: Requested temperature
      description: Requested temperature
      selector:
        entity: {}
    outdoor_temperature:
      name: Outdoor temperature
      description: Outdoor temperature sensor
      selector:
        entity: {}
    turn_off_time:
      name: Turn off time
      description: Time when heating should be turned off
      selector:
        time:
    turn_on_time:
      name: Turn on time
      description: Time when heating should be turned on
      selector:
        time:
variables:
  outdoor_temperature: !input outdoor_temperature
  indoor_temperature: !input indoor_temperature
  requested_temperature: !input requested_temperature
  input_switch: !input switch
  off_time: !input turn_off_time
  on_time: !input turn_on_time
trigger:
  platform: time_pattern
  minutes: /30
condition: ''
action:
  - choose:
      - conditions:
          condition: or
          conditions:
            - condition: and
              conditions:
                - condition: 'template'
                  value_template: "{{ outdoor_temperature <  20 }}"
                - condition: 'template'
                  value_template: '{{ requested_temperature < indoor_temperature }}'
                - condition: time
                  after: !input turn_on_time
                  before: !input turn_off_time
            - condition: and
              conditions:
                - condition: device
                  type: is_off
                  device: input_switch
                  domain: switch
                  for:
                    hours: 2
                    minutes: 0
                    seconds: 0
                - condition: 'template'
                  value_template: '{{ requested_temperature < indoor_temperature }}'
                - condition: time
                  after: !input turn_on_time
                  before: !input turn_off_time
        sequence:
          - type: turn_on
            device: input_switch
            domain: switch
    default:
      - type: turn_off
        device: input_switch
        domain: switch
mode: single
